import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";


export const downloadReport = () => {

  const pdf = new jsPDF("p", "mm", "a4");


  // Header
  pdf.setFillColor(15, 23, 42);
  pdf.rect(
    0,
    0,
    210,
    35,
    "F"
  );


  pdf.setTextColor(255,255,255);

  pdf.setFontSize(22);

  pdf.text(
    "CrimeVision AI",
    15,
    15
  );


  pdf.setFontSize(11);

  pdf.text(
    "Karnataka Police Crime Analytics",
    15,
    23
  );


  pdf.text(
    "AI Generated Investigation Report",
    15,
    30
  );



  // Report Information

  pdf.setTextColor(0,0,0);

  pdf.setFontSize(16);

  pdf.text(
    "Investigation Summary",
    15,
    50
  );



  autoTable(pdf,{

    startY:58,

    head:[
      [
        "Field",
        "Details"
      ]
    ],

    body:[

      [
        "Report ID",
        "CVAI-2026-001"
      ],

      [
        "FIR Number",
        "FIR-2026-001245"
      ],

      [
        "Crime Type",
        "Armed Robbery"
      ],

      [
        "Location",
        "Electronic City, Bengaluru"
      ],

      [
        "Officer",
        "Officer001"
      ],

      [
        "Priority",
        "HIGH"
      ]

    ]

  });



  // Evidence

  pdf.setFontSize(16);

  pdf.text(
    "Evidence Analysis",
    15,
    pdf.lastAutoTable.finalY + 15
  );



  autoTable(pdf,{

    startY:
    pdf.lastAutoTable.finalY + 22,

    head:[
      [
        "Evidence",
        "Status"
      ]
    ],

    body:[

      [
        "CCTV Footage",
        "Analysed"
      ],

      [
        "Witness Statements",
        "Verified"
      ],

      [
        "Criminal History",
        "Matched"
      ],

      [
        "Location Pattern",
        "Detected"
      ]

    ]

  });



  // AI Section

  let finalY =
  pdf.lastAutoTable.finalY + 20;


  pdf.setFontSize(16);

  pdf.text(
    "AI Investigation Result",
    15,
    finalY
  );


  pdf.setFontSize(11);


  const summary =
  "CrimeVision AI analysed FIR records, CCTV footage, witness statements and criminal history. Pattern analysis indicates connection with Gang Alpha. AI confidence score: 94%.";


  pdf.text(
    summary,
    15,
    finalY + 10,
    {
      maxWidth:180
    }
  );



  // Footer

  pdf.setFontSize(10);

  pdf.setTextColor(100);


  pdf.text(

    "Generated by CrimeVision AI | Government of Karnataka Police",

    15,

    285

  );


  pdf.save(
    "CrimeVision_Investigation_Report.pdf"
  );


};